spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: akk
    password: akk6881385
    url: jdbc:mysql://115.159.35.121/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  #配置了这个就不会返回为NULL的参数
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 115.159.35.121
    port: 6379
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level: debug

wechat:
  mpAppId: wx8b20c44179a091b4
  mpAppSecret: de419bbffabaa12840f16c5035391a7f
  mchId: 1488013852
  mchKey: uxNWYgnY95q9ieTAggUmMelvqNrhzylf
  keyPath: C:\SoftWare\Weixin\apiclient_cert.p12
  notifyUrl: http://www.akakakaka.cn:8080/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://www.akakakaka.cn:8080
  sell: http://www.akakakaka.cn:8080
